@apikey = 161713fd-87aa-4872-af04-d37977cf6440
@subscription = 9d375fc8-5ba7-4f82-95db-e0e069a59d29
@url = https://idmp.who-umc.org/fhir

### FCAT 38 - List subscription topics
GET {{url}}/SubscriptionTopic
Ocp-Apim-Subscription-Key: {{apikey}}

### FCAT 38 - Create new subscription
POST  {{url}}/Subscription
Ocp-Apim-Subscription-Key: {{apikey}} 

< ./subscription-email.json

### FCAT 38 - Get subscription
GET  {{url}}/Subscription/{{subscription}}
Ocp-Apim-Subscription-Key: {{apikey}}
 
### FCAT 38 - Create faked event
GET {{url}}/TriggerEvent/mpd/123
Ocp-Apim-Subscription-Key: {{apikey}}
 
### FCAT 38 - List subscriptions
GET {{url}}/Subscription
Ocp-Apim-Subscription-Key: {{apikey}}
 
### FCAT 38 - Delete subscription
DELETE  {{url}}/Subscription/{{subscription}}
Ocp-Apim-Subscription-Key: {{apikey}}
