
# ╭──────────────────────────────ImplementationGuide-gatekeeper.json───────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: umcterminologies.org
canonical: https://build.fhir.org/ig/Uppsala-Monitoring-Centre/WHO-UMC-IDMP-Service
version: 1.0.0
name: UmcIDMPManagement
title: UMC IDMP Request and Publish API 
status: active
publisher:
  name: Uppsala Monitoring Centre
  url: http://www.who-umc.org
contact:
  - name: Uppsala Monitoring Centre
    telecom:
      - system: url
        value: http://www.who-umc.org

description: The UMC IDMP API supports management and publishing of PhPIDs and GSIDs as part of the ISO IDMP standard
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
license: CC0-1.0
fhirVersion: 5.0.0
# dependencies:
#   hl7.fhir.uv.ips: current
parameters:
  show-inherited-invariants: false
  produce-jekyll-data: true
  special-url:
  - http://umcterminologies.org/StructureDefinition/parent-phpid
  - http://umcterminologies.org/StructureDefinition/pdfCharacteristics
copyrightYear: 2025+
releaseLabel: CI Build

instanceOptions:
  manualSliceOrdering: true

FSHOnly: false

pages:
  index.md:
    title: UMC IDMP Request and Publish API   
  background.md:
    title: Background
  operatingModel.md:
    title: Operating model   
  phpIdRequest.md:
    title: PhPID (AdministrableProductDefinition) request   
  published-resources.md:
    title: Publish
  #substanceRequest.md:
  #  title: GSID (Substance) request   
  #authentication.md:
  #  title: Authentication
  #subscription.md:
  #  title: Change management
  #versioning.md:
  #  title: Versioning
  profiles.md:
    title: Profiles
  terminologies.md:
    title: Terminologies
  downloads.html:
    title: Useful downloads
  history.html:
    title: IG change history

menu:
  IG Home: index.html
  Background: background.html
  Requesting PhPID:
    Operating model: operatingModel.html
    PhPID request: phpIdRequest.html
    #GSID request: substanceRequest.html
  Publish: published-resources.html
  #Change management:
  #  Change management: subscription.html
  #  Versioning: versioning.html
  #Authentication: authentication.html
  # Specifications:
  #   Profiles: profiles.html
  #   Terminology: terminologies.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html			
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R5/index.html
    Downloads: downloads.html


# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:

resources:
  Task/template-generated-by-server-phpid-req:
    name: Task Request for a new PhPID
    description: A template for how a Task that is used to request a new PhPID (AdministrableProductDefinition) can be structured.
  Task/task-completed-phpid:
    name: Task Completed with PhPID
    description: An example of a completed task with output values that include PhPID and UMC Product ID.
  AdministrableProductDefinition/UTPHPID102Y0G2TFV6GU6:
    name: AdministrableProductDefinition level 4
    description: AdministrableProductDefinition returned by the server on level 4.
  AdministrableProductDefinition/UTPHPID5F4A1M772SP14T:
    name: AdministrableProductDefinition level 3
    description: AdministrableProductDefinition on level 3. Linked from a level 4 APD.
  AdministrableProductDefinition/UTPHPID5EPH9X6P86CM6L:
    name: AdministrableProductDefinition level 2
    description: AdministrableProductDefinition on level 2. Linked from a level 4 APD.
  AdministrableProductDefinition/UTPHPID2C4FBA65KDM1P6:
    name: AdministrableProductDefinition level 1
    description: AdministrableProductDefinition on level 1. Linked from a level 4, 3 and 2 APD.
  SubstanceDefinition/UTGSID1ZH2AGD3LL96N:
    name: Substance (METHOTREXATE)
    description: An example of a GSID publisehed as a SubstanceDefinition  
  SubstanceDefinition/UTGSID8VJD2KSL8JG9N:
    name: Substance (METHOTREXATE DISODIUM)
    description: An example of a GSID (salt variant) publisehed as a SubstanceDefinition  
  MedicinalProductDefinition/UMCPIDCHE7S94JFG8TE3D5:
    name: MedicinalProductDefinition (Micardis)
    description: Example of a WHODrug product published as a MedicinalProductDefinition.
  MedicinalProductDefinition/UMCPIDDEU4CVM68UK905BO:
    name: MedicinalProductDefinition (Perfalgan)
    description: Example of a WHODrug product published as a MedicinalProductDefinition.
  